language: python

python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.3"
env:
    - WTFORMS=WTForms==1.0.5
    - WTFORMS=https://github.com/wtforms/wtforms/archive/master.zip

install:
    - pip install $WTFORMS
    - pip install -r requirements.txt

script:
    - nosetests

after_success:
    - pip install coveralls
    - coverage run --source=flask_wtf setup.py -q nosetests
    - coveralls

notifications:
    email: false
