language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"

env:
    - WTFORMS=WTForms==1.0.5
    - WTFORMS=WTForms==2.0.2

install:
    - pip install $WTFORMS
    - pip install -r requirements.txt

script:
    - nosetests

after_success:
    - pip install coveralls
    - coverage run --source=flask_wtf setup.py -q nosetests
    - coveralls

notifications:
    email: false
