language: python

python:
    - "2.6"
    - "2.7"

script:
    - nosetests

after_success:
    - pip install coveralls
    - coverage run --source=flask_wtf setup.py -q nosetests
    - coveralls

notifications:
    email: false
