sudo: false
language: python

python:
    - 2.6
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - 3.6-dev

install:
    - pip install -r test-requirements.txt

script:
    - nosetests tests

after_success:
    - pip install coveralls
    - coverage run --source=flask_wtf -m nose tests
    - coveralls

notifications:
    email: false
